### ISSUE TITLE
[Bug] Error: Command failed: cat /mnt/host/sys/class/net/eth0/speed

### ISSUE THREAD

**Issue by SuimgPhilip** [MauriceNino/dashdot#727] opened 2023-04-29 09:01 UTC
### Description of the bug

[root@gateway-suimg ~]# docker container run -it   -p 3001:3001   -v /:/mnt/host:ro   --privileged   mauricenino/dashdot
yarn run v1.22.19
$ node .
listening on *:3001
Using default network interface "eth0"
Using host os version from "/mnt/host/etc/os-release"
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: cat /mnt/host/sys/class/net/eth0/speed
cat: read error: Invalid argument

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'cat /mnt/host/sys/class/net/eth0/speed',
  stdout: '',
  stderr: 'cat: read error: Invalid argument\n'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Where is your instance running?

 Alibaba Cloud Elastic Compute Service 

### Additional context

``` shell
[root@gateway-suimg ~]# route | grep '^default' | grep -o '[^ ]*$'
eth0
[root@gateway-suimg ~]# ip route get 8.8.8.8 | sed -n 's/.*dev \([^\ ]*\).*/\1/p'
eth0
[root@gateway-suimg ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
[root@gateway-suimg ~]# docker -v
Docker version 20.10.21, build baeda1f
[root@gateway-suimg ~]# 
```

**Comment by MauriceNino** [comment] 2023-04-29 10:19
Hi there, thanks for all the info. I am closing this in favor of #715 - it is the same issue, just with different install methods.

The problem is that the network interface speed cannot be determined, and I did not check for that. A fix is currently on the way.

**Closed by MauriceNino** 2023-04-29 10:19 UTC
Labels: type: bug
