### ISSUE TITLE
[Bug] only main storage size shown

### ISSUE THREAD

**Issue by ristein** [MauriceNino/dashdot#917] opened 2023-09-09 12:48 UTC
### Description of the bug

![image](https://github.com/MauriceNino/dashdot/assets/55446611/73fdf037-de37-4726-b3c5-1f3a15ed416c)
usage of secondary drives is wrongly at 0%, empty

### Info output of dashdot cli

```shell
docker exec dashdot yarn cli info
yarn run v1.22.19
$ node dist/apps/cli/main.js info
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'systeminformation'
Require stack:
- /app/dist/apps/cli/apps/cli/src/main.js
- /app/dist/apps/cli/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (/app/dist/apps/cli/main.js:32:36)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/app/dist/apps/cli/apps/cli/src/main.js:26:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/apps/cli/apps/cli/src/main.js',
    '/app/dist/apps/cli/main.js'
  ]
}

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What browsers are you seeing the problem on?

Firefox

### Where is your instance running?

Linux Server

### Additional context

in [benphelps/homepage](https://github.com/benphelps/homepage) I needed to mount every drive via "-v /mnt/drive:/mnt/drive:ro" to get sizes shown. But this does not help here.

**Comment by MauriceNino** [comment] 2023-10-25 12:20
Hi there, sorry for the late answer. Have you mounted the host drive as documented in the examples? `-v /:/mnt/host:ro`?

**Comment by ristein** [comment] 2023-10-25 16:44
yes. full command is here: https://github.com/MauriceNino/dashdot/issues/924#issue-1931294121

**Comment by MauriceNino** [comment] 2024-01-06 18:45
Sorry again for the delay!

Can you please try the latest dev container `mauricenino/dashdot:dev` and if that does not fix your issues, post the following command?

```
docker exec CONTAINER yarn cli raw-data --storage
```

**Comment by ristein** [comment] 2024-01-06 19:14
@MauriceNino 
dev did not help

![image](https://github.com/MauriceNino/dashdot/assets/55446611/5e250650-47bd-4779-8d94-de0764c9d342)

[docker exec dashdot yarn cli raw-da.txt](https://github.com/MauriceNino/dashdot/files/13850921/docker.exec.dashdot.yarn.cli.raw-da.txt)

**Comment by MauriceNino** [comment] 2024-01-06 19:54
Are you running in some kind of virtualized environment? Your sizes array is completely empty, which is very weird to me.

**Comment by ristein** [comment] 2024-01-06 20:17
I'm running dicker directly on ubuntu

**Comment by MauriceNino** [comment] 2024-01-06 20:59
@ristein Can you show me the config you use to start the container?

**Comment by ristein** [comment] 2024-01-06 22:39
docker run -it --name dashdot -p 12137:3001 --privileged --restart=unless-stopped --env DASHDOT_SHOW_HOST="true" --env DASHDOT_SHOW_DASH_VERSION="bottom_right" --env DASHDOT_ALWAYS_SHOW_PERCENTAGES="true" --env DASHDOT_PAGE_TITLE="dash.example.com" --env DASHDOT_NETWORK_LABEL_LIST="type,speed_up,speed_down,interface_speed,public_ip" -v /:/mnt/host:ro mauricenino/dashdot

**Comment by MauriceNino** [comment] 2024-01-07 09:57
Hm, that is indeed very weird. I would think there is some kind of access problem. Can you try restarting the container completely from the ground up (delete the container, delete the image) and then rerunning the command?

Also, do normal UNIX utils give you some information on your host and inside the container?
To test it, please execute these commands as well and paste the outputs:

```
df -h
docker exec dashdot df -h
```

**Comment by ristein** [comment] 2024-01-07 11:48
"docker exec dashdot df -h" correctly shows all drives alongside all those loop-devices and docker volumes, which "df -h" does not show:
```
(only relevant lines, full output in file)
$ docker exec dashdot df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                   1.8T    722.4G   1015.9G  42% /
tmpfs                    64.0M         0     64.0M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/mapper/luks-9e54f936-e7c0-4ece-ab06-89776d516967    1.8T    722.4G   1015.9G  42% /mnt/host
/dev/nvme0n1p2          739.1M    420.2M    265.1M  61% /mnt/host/boot
/dev/nvme0n1p1          548.9M      6.2M    542.7M   1% /mnt/host/boot/efi
/dev/mapper/WDraid      915.7G    537.4G    331.7G  62% /mnt/host/mnt/WDraid
/dev/mapper/TOSHI1       12.6T     11.4T    612.3G  95% /mnt/host/mnt/TOSHI1
``` 
[df-h.txt](https://github.com/MauriceNino/dashdot/files/13853222/df-h.txt)

after removing container and image and starting containers, these are the outputs of rawdata:
[dashdot-rawdata.txt](https://github.com/MauriceNino/dashdot/files/13853207/dashdot-rawdata.txt)
[dashdot-dev-rawdata.txt](https://github.com/MauriceNino/dashdot/files/13853208/dashdot-dev-rawdata.txt)

**Comment by MauriceNino** [comment] 2024-01-07 12:11
Hm, aside from your data being severely malformed, I see no sizes again. Are there any relevant errors in the logs?

**Comment by ristein** [comment] 2024-01-07 12:21
where are the logs?

**Comment by MauriceNino** [comment] 2024-01-07 12:45
From your docker container https://docs.docker.com/config/containers/logging/

**Comment by ristein** [comment] 2024-01-07 16:21
I did docker logs dashdot but nothing suspicious there.
[logs.txt](https://github.com/MauriceNino/dashdot/files/13854148/logs.txt)

**Comment by MauriceNino** [comment] 2024-01-07 17:31
That is very weird. I cannot really help you, as on a normal Ubuntu install running docker, this information should be available. The setup on the public demo is exactly the same. The only thing you could do (if you have the technical knowledge) is to install dashdot locally ([documentation](https://getdashdot.com/docs/install/from-source)) and start it from there.

If this still does not get the required variables in the storage sizes, then there is definitely something wrong with your system.

Other than that, my best guess is that there is some kind of access problem with your Docker installation. As I can't reproduce it and the data is simply not here, I will have to close this issue for now, though.

**Closed by MauriceNino** 2024-01-07 17:31 UTC
Labels: type: bug
