### ISSUE TITLE
[Bug] docker image download slow

### ISSUE THREAD

**Issue by ristein** [MauriceNino/dashdot#998] opened 2024-01-07 11:37 UTC
### Description of the bug

downloading images is slow.
0607ea55e6fb only loads at 40kb/s and takes 10min to complete.
canceling and restarting sometimes makes it faster.

![Screenshot_20240107-123239_Termux](https://github.com/MauriceNino/dashdot/assets/55446611/55a02b06-8eee-466f-9761-70a26edc27c5)

### How to reproduce

remove dashdot
remove image
start container

**Comment by ristein** [comment] 2024-01-07 11:39
can I try ghcr.io/maricenino/dashdot and ghcr.io/maricenino/dashdot:dev?
Are these the same images and also updated?

**Comment by MauriceNino** [comment] 2024-01-07 12:08
For me, the download completes in under 5 seconds (after deleting all my images locally), so it sounds like you are having some network troubles, or maybe you download a lot of images and DockerHub throttles your connection?

![image](https://github.com/MauriceNino/dashdot/assets/18658092/512212e7-4f13-42a2-83cf-ba06efc5e556)

But yes, the images on GitHub are up-to-date and can also be used.

Will close this, because it is not reproducible on my end.

**Closed by MauriceNino** 2024-01-07 12:08 UTC
Labels: type: bug
